export const LOAD_FLIGHTS_SUCCESS = 'LOAD_FLIGHTS_SUCCESS'
export const ADD_FLIGHT_SUCCESS = 'ADD_FLIGHT_SUCCESS'
export const ADD_LIKE_SUCCESS = "ADD_LIKE_SUCCESS"
export const DELETE_FLIGHT_SUCCESS = "DELETE_FLIGHT_SUCCESS"
