# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 299069924d5c333e82d35d21da791b58902ed519c945bbb0d35b177522d8df2faaa49853aaee59245a317fba68e7c49ac56a5954a302b1a5c118a7176c183df8

test:
  secret_key_base: 1fb23392ea2ef9f296b42aed87a18cbcf1bf7154b372884862f6fdd224f9b909c2f8464c853d01dd40b3dd7a0aa1990e0431964ba6b1dd7504b12d34358ade6e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
